sudo: required
services:
  - docker

env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)
    #- CLOUDSDK_CORE_DISABLE_PROMPTS=1 # google CLI no user input

before_install:
  # Google cloud setup
#  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
#  - curl https://sdk.cloud.google.com | bash > /dev/null;
#  - source $HOME/google-cloud-sdk/path.bash.inc
#  - gcloud components update kubectl
#  - gcloud auth activate-service-account --key-file service-account.json
#  - gcloud config set project skillful-berm
#  - gcloud config set compute/zone us-central1-a
#  - glcoud container clusters get-credentials multi-cluster
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # build test
  - docker build -t drnickit/react-test -f ./client/profiles/dev/Dockerfile ./client

script:
  - docker run -e CI=true drnickit/react-test npm run test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master