sudo: required
services:
  - docker

before_install:
  - docker build -t drnickit/react-test -f ./client/profiles/dev/Dockerfile ./client

script:
  - docker run -e CI=true drnickit/react-test npm run test

after_success:
  - docker build -t drnickit/multi-client -f ./client/profiles/prod/Dockerfile ./client
  - docker build -t drnickit/multi-nginx -f ./nginx/profiles/prod/Dockerfile ./nginx
  - docker build -t drnickit/multi-server -f ./server/profiles/prod/Dockerfile ./server
  - docker build -t drnickit/multi-worker -f ./worker/profiles/prod/Dockerfile ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push drnickit/multi-client
  - docker push drnickit/multi-nginx
  - docker push drnickit/multi-server
  - docker push drnickit/multi-worker

#deploy:
#  provider: elasticbeanstalk
#  region: us-west-1
#  app: multi-docker
#  env: MultiDocker-env
#  bucket_name: elasticbeanstalk-us-west-1-306476627547
#  bucket_path: docker-multi
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: $AWS_SECRET_KEY
