apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3 # The number of Pod's to create
  selector:
    matchLabels:
      component: web
  template: #what doese each pod/container have to define
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: drnickit/multi-client
          ports:
            - containerPort: 3000