apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3 # The number of Pod's to create
  selector:
    matchLabels:
      component: server
  template: #what doese each pod/container have to define
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: drnickit/multi-server
          ports:
            - containerPort: 5000