apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1 # The number of Pod's to create
  selector:
    matchLabels:
      component: worker
  template: #what doese each pod/container have to define
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: worker
          image: drnickit/multi-worker